
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/header_folder";
import Footer from "@/app/components/footer_folder";
import { AuthProvider } from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Technology",
  description: "Generated by Sebaxtian",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className} >
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </AuthProvider>
  );
}
